Tensor 常見的形式
---
* scalar
* vetor
* matrix
* n-dim tensor

In [4]:
import torch
from torch import tensor

Sclar
--
數值

In [5]:
x = tensor(42.)
x

tensor(42.)

In [6]:
x.dim()

0

In [7]:
2 * x

tensor(84.)

In [8]:
x.item()

42.0

Vector
--
在 NN 中代表特徵

In [9]:
v = tensor([1.5,-0.5,3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [10]:
v.dim()

1

In [11]:
v.size()

torch.Size([3])

Matrix
--
    ＊矩陣 通常是多維

In [12]:
M = tensor([ [1,2] , [3,4] ])
M

tensor([[1, 2],
        [3, 4]])

In [13]:
M.matmul(M)

tensor([[ 7, 10],
        [15, 22]])

In [14]:
tensor([1. , 0.]).matmul(M)

RuntimeError: expected m1 and m2 to have the same dtype, but got: float != long long

In [16]:
M * M

tensor([[ 1,  4],
        [ 9, 16]])